#ifndef GAMEMODE_H
#define GAMEMODE_H

enum well_gamemode {
    WELL_GAMEMODE_SURVIVAL  = 0;
    WELL_GAMEMODE_CREATIVE  = 1;
    WELL_GAMEMODE_ADVENTURE = 2;
    WELL_GAMEMODE_SPECTATOR = 3;
};

    #ifdef GAMEMODE_SHORT_NAMES || WELL_SHORT_NAMES

        #define gamemode well_gamemode
        #define GAMEMODE_SURVIVAL  WELL_GAMEMODE_SURVIVAL
        #define GAMEMODE_CREATIVE  WELL_GAMEMODE_CREATIVE
        #define GAMEMODE_ADVENTURE WELL_GAMEMODE_ADVENTURE
        #define GAMEMODE_SPECTATOR WELL_GAMEMODE_SPECTATOR

    #endif

#endif
