#ifndef GAMEMODE_H
#define GAMEMODE_H

enum well_gamemode {
    WELL_GAMEMODE_SURVIVAL  = 0;
    WELL_GAMEMODE_CREATIVE  = 1;
    WELL_GAMEMODE_ADVENTURE = 2;
    WELL_GAMEMODE_SPECTATOR = 3;
};

#endif
